apiVersion: v2
name: agenthealth
description: Passive AgentHealth checks and experimental AHP serving
type: application
version: 0.12.1
appVersion: "v0.12.1"
kubeVersion: ">=1.29.0-0"
annotations:
  org.opencontainers.image.source: https://github.com/TheAgentHealth/agenthealth
