#!/usr/bin/env python3
"""Generate status tables from docs/status.json; --check rejects documentation drift."""
import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]

def render():
    data = json.loads((ROOT / 'docs/status.json').read_text())
    lines = ['# Capability status', '', '<!-- Generated by scripts/generate_status.py; edit docs/status.json. -->', '',
             f'Published software: **{data["software_version"]}**, pre-1.0.', '',
             'Release status and source-only work are separate. Controlled SDK tests do not',
             'complete broader product interoperability. Historical releases retain their scope.', '',
             '| Phase | Status | Documentation | Examples or validation |', '|---|---|---|---|']
    for phase in data['phases']:
        lines.append('| ' + ' | '.join(phase[k] for k in ('phase', 'status', 'documentation', 'validation')) + ' |')
    lines.extend(['', 'See [stabilization](stabilization.md) for current work and',
                  '[distribution](distribution.md) for synchronized release verification.', ''])
    return '\n'.join(lines)

if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    target = ROOT / 'docs/phase-status.md'
    text = render()
    data = json.loads((ROOT / 'docs/status.json').read_text())
    version = data['software_version']
    table = ['| Use it as | Get it here | Installation guide |', '|---|---|---|']
    for row in data['distributions']:
        table.append('| ' + ' | '.join(row[key].format(version=version, numeric_version=version.removeprefix('v'))
                                       for key in ('name', 'download', 'guide')) + ' |')
    readme = ROOT / 'README.md'
    current = readme.read_text()
    start = '<!-- generated: distributions:start -->'
    end = '<!-- generated: distributions:end -->'
    before, remainder = current.split(start, 1)
    _, after = remainder.split(end, 1)
    rendered_readme = before + start + '\n' + '\n'.join(table) + '\n' + end + after
    if args.check:
        if target.read_text() != text or current != rendered_readme:
            raise SystemExit('Status documentation is stale; run python3 scripts/generate_status.py')
    else:
        target.write_text(text)
        readme.write_text(rendered_readme)
