apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- job.yaml
- cronjob.yaml
images:
- name: ghcr.io/theagenthealth/agenthealth
  newTag: v0.12.0
configMapGenerator:
- name: agenthealth-config
  files:
  - config.yaml=agenthealth.yaml
